/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.janelia.simview.klb.jni;

public class KlbImageHeader {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected KlbImageHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(KlbImageHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        KlbJNI.delete_KlbImageHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setXyzct(long[] value) {
    KlbJNI.KlbImageHeader_xyzct_set(swigCPtr, this, value);
  }

  public long[] getXyzct() {
    return KlbJNI.KlbImageHeader_xyzct_get(swigCPtr, this);
  }

  public void setPixelSize(float[] value) {
    KlbJNI.KlbImageHeader_pixelSize_set(swigCPtr, this, value);
  }

  public float[] getPixelSize() {
    return KlbJNI.KlbImageHeader_pixelSize_get(swigCPtr, this);
  }

  public void setDataType(short value) {
    KlbJNI.KlbImageHeader_dataType_set(swigCPtr, this, value);
  }

  public short getDataType() {
    return KlbJNI.KlbImageHeader_dataType_get(swigCPtr, this);
  }

  public void setCompressionType(short value) {
    KlbJNI.KlbImageHeader_compressionType_set(swigCPtr, this, value);
  }

  public short getCompressionType() {
    return KlbJNI.KlbImageHeader_compressionType_get(swigCPtr, this);
  }

  public void setBlockSize(long[] value) {
    KlbJNI.KlbImageHeader_blockSize_set(swigCPtr, this, value);
  }

  public long[] getBlockSize() {
    return KlbJNI.KlbImageHeader_blockSize_get(swigCPtr, this);
  }

  public KlbImageHeader(KlbImageHeader p) {
    this(KlbJNI.new_KlbImageHeader__SWIG_0(KlbImageHeader.getCPtr(p), p), true);
  }

  public KlbImageHeader() {
    this(KlbJNI.new_KlbImageHeader__SWIG_1(), true);
  }

  public int readHeader(String filename) {
    return KlbJNI.KlbImageHeader_readHeader(swigCPtr, this, filename);
  }

  public long getNumBlocks() {
    return KlbJNI.KlbImageHeader_getNumBlocks(swigCPtr, this);
  }

  public long calculateNumBlocks() {
    return KlbJNI.KlbImageHeader_calculateNumBlocks(swigCPtr, this);
  }

  public long getSizeInBytes() {
    return KlbJNI.KlbImageHeader_getSizeInBytes(swigCPtr, this);
  }

  public long getSizeInBytesFixPortion() {
    return KlbJNI.KlbImageHeader_getSizeInBytesFixPortion(swigCPtr, this);
  }

  public long getBytesPerPixel() {
    return KlbJNI.KlbImageHeader_getBytesPerPixel(swigCPtr, this);
  }

  public long getBlockSizeBytes() {
    return KlbJNI.KlbImageHeader_getBlockSizeBytes(swigCPtr, this);
  }

  public java.math.BigInteger getImageSizeBytes() {
    return KlbJNI.KlbImageHeader_getImageSizeBytes(swigCPtr, this);
  }

  public java.math.BigInteger getImageSizePixels() {
    return KlbJNI.KlbImageHeader_getImageSizePixels(swigCPtr, this);
  }

  public long getBlockCompressedSizeBytes(long blockId) {
    return KlbJNI.KlbImageHeader_getBlockCompressedSizeBytes(swigCPtr, this, blockId);
  }

  public java.math.BigInteger getBlockOffset(long blockIdx) {
    return KlbJNI.KlbImageHeader_getBlockOffset(swigCPtr, this, blockIdx);
  }

  public java.math.BigInteger getCompressedFileSizeInBytes() {
    return KlbJNI.KlbImageHeader_getCompressedFileSizeInBytes(swigCPtr, this);
  }

  public void setDefaultBlockSize() {
    KlbJNI.KlbImageHeader_setDefaultBlockSize(swigCPtr, this);
  }

}
